
GET http://localhost:3000/addresses
Authorization:eafi0uispesac0o2wrqx
###
GET http://localhost:3000/addresses/100
Authorization:y06e3lmhet09xcguy8nj
###
POST http://localhost:3000/addresses
Content-Type: application/json
Authorization:y06e3lmhet09xcguy8nj

{
  "full_name":"ddsad",
  "city": "jericho",
    "phone": "5558552458",
    "street": "amman",
    "country": "defwf",
    "postal_code": "54433",
    "address_line1": "FWefwf",
    "address_line2": "fewfwf"
}

###
PUT http://localhost:3000/addresses/7
Content-Type: application/json
Authorization:eafi0uispesac0o2wrqx

{
  "city": "hrhrhrh",
    "street": "thrhtrhrh",
    "country": "ggrgrhgrg",
    "postal_code": 433443333433,
    "address_line2": "grhrhrh"
}
###
DELETE  http://localhost:3000/addresses/101
Authorization:zG3vLifO2bXQHANGTiZNCdA43SZZDe

