###LOCALHOST 
GET http://localhost:3000/category
###
GET http://localhost:3000/category/handpicked
###
GET http://localhost:3000/category/top
###
GET http://localhost:3000/category/mobile




###API
GET http://158.176.7.102:3000/category
###
GET http://158.176.7.102:3000/category/handpicked
###
GET http://158.176.7.102:3000/category/top
###
GET http://158.176.7.102:3000/category/mobile