POST http://localhost:3000/orders
Authorization: 4rpvjk2krzslmysvegcp
Content-Type: application/json

{
  "order_address": {
    "city": "Berlin",
    "phone": "2595565892",
    "street": "stugt St",
    "country": "Germany",
    "postal_code": "59784",
    "address_line1": "ELK GROVE CA 95758",
    "address_line2": " CA 95758"
  },
  "payment_method": "Credit Card"
}
###
GET http://localhost:3000/orders/info/11
Authorization: u07bkqwce3u7ffvspmxp

###
GET http://localhost:3000/orders
Authorization: u07bkqwce3u7ffvspmxp
###


POST http://localhost:3000/orders/reorder/156
Authorization: zG3vLifO2bXQHANGTiZNCdA43SZZDe
###

PUT http://localhost:3000/orders/156/cancel
Authorization: zG3vLifO2bXQHANGTiZNCdA43SZZDe
###




POST http://158.176.7.102:3000/orders
Authorization: 2vE1KGZDV38vw6avdC6OER4HL5OVLl
Content-Type: application/json

{
  "order_address": {
    "full_name": "ahamad",
    "city": "Berlin",
    "phone": "2563335892",
    "street": "stugt St",
    "country": "Germany",
    "postal_code": "59784",
    "address_line1": "ELK GROVE CA 95758",
    "address_line2": " CA 95758"
  },
  "payment_method": "Credit Card"
}
###
GET http://158.176.7.102:3000/orders/info/1
Authorization: vpunzi812k7dwobzuj92

###
GET http://158.176.7.102:3000/orders
Authorization: 2vE1KGZDV38vw6avdC6OER4HL5OVLl
###


POST http://158.176.7.102:3000/orders/reorder/156
Authorization: zG3vLifO2bXQHANGTiZNCdA43SZZDe
###

PUT http://158.176.7.102:3000/orders/156/cancel
Authorization: zG3vLifO2bXQHANGTiZNCdA43SZZDe
###
