### LOCALHOST
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "username": "ka2fessejo",
  "email": "wdwdwf3e@example.com",
  "password": "Mh&55r58r55",
  "first_name": "John",
  "last_name": "Doe",
  "mobile": "1234567890",
  "birth_date": "1990-01-01"
}
###
POST http://localhost:3000/users/signin
Content-Type: application/json

{
  "email": "wdwd3ss3ww3e@example.com",
  "password": "Mh&55r58r55"
}
###
GET http://localhost:3000/users/signout 
Authorization:0YDybsf1YaLHZ9efbt9Mr
###
#INFORMATION
GET http://localhost:3000/users/53
Authorization:AkBvdnZFJCRbUFop4evQlghnAjr2ox
###
#UPDATE INFORMATION
PUT http://localhost:3000/users/54
Content-Type: application/json
Authorization:Ks9dfJxuRKoZNXoie6yH

{
  "first_name": "ukuukuku",
  "birth_date": "1997-01-01T00:00:00.000Z"
}
###
#DELETE USER ACCOUNT 
DELETE http://localhost:3000/users/32
Authorization:YrDWOklpKkaWl2OUTcH9lLTk5pacUc
###
PUT  http://localhost:3000/users/change-password
Content-Type: application/json
Authorization:Ks9dfJxuRKoZNXoie6yH

{
  "currentPassword":"Mh&55r58r55",
  "newPassword":"JsMh&55r58r55"
}

###
PUT  http://localhost:3000/users/change-username
Content-Type: application/json
Authorization:Ks9dfJxuRKoZNXoie6yH

{
  "newUsername":"Mh&55r58r55"
}






### API 
POST http://158.176.7.102:3000/users/signup
Content-Type: application/json

{
  "username": "fadiH",
  "email": "fadih@example.com",
  "password": "Fadi@123",
  "first_name": "John",
  "last_name": "Doe",
  "mobile": "1234567890",
  "birth_date": "1990-01-01"
}
###
POST http://158.176.7.102:3000/users/signin
Content-Type: application/json

{
  "email": "jjknnn@example.com",
  "password": "Mh&55r58r55"
}
###
GET http://158.176.7.102:3000/users/signout 
Authorization:VFj4M8AdnfvKWtpePZjqz7BwB4tLWX 
###
#INFORMATION
GET http://158.176.7.102:3000/users/53
Authorization:SJtNn4T39zy1jqOmxkJH
###
#UPDATE INFORMATION
PUT http://158.176.7.102:3000/users/45
Content-Type: application/json
Authorization:SJtNn4T39zy1jqOmxkJH

{
  "first_name": "bat5ya",
  "last_name": "fefefeffefe",
  "mobile": "5687657557",
  "birth_date": "1990-01-01"
}
###
#DELETE USER ACCOUNT 
DELETE http://158.176.7.102:3000/users/32
Authorization:YrDWOklpKkaWl2OUTcH9lLTk5pacUc
###
PUT http://158.176.7.102:3000/users/change-password
Content-Type: application/json
Authorization:GuVO24udZC3R7ufHYxaz

{
  "currentPassword":"Mh&55r58r55",
  "newPassword":"Mhwww&55r58r55444444"
}

###
PUT http://158.176.7.102:3000/users/change-username
Content-Type: application/json
Authorization:0LExz9in2mqO43v8eyjD

{
"newUsername":"kratos"
}
