GET http://localhost:3000/admin/users?createdStartDate=1962&createdEndDate=2024
Authorization:fadi

###
GET http://localhost:3000/admin/products?categoryId=2&type=category
Authorization:fadi

###
GET http://localhost:3000/admin/users?maxAge=40&minAge=18
Authorization:fadi


###
GET http://localhost:3000/admin/users?loginStartDate=2024-01-01&loginEndDate=2024-01-31
Authorization:fadi
###
GET http://localhost:3000/admin/users?country=Italy
Authorization:fadi


### LOCALHOST
PUT http://localhost:3000/admin/users
Content-Type: application/json
Authorization:fadi

{   
    "id":1,
  "username": "kattt2fessejo",
  "email": "wttttwf3e@example.com",
  "password": "Mhttt&55r58r55",
  "first_name": "John",
  "last_name": "Dotte",
  "mobile": "1234567890",
  "birth_date": "1990-01-01"
}