GET http://localhost:3000/category
###
GET http://localhost:3000/brand
###

#############################################
# USERS

POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "username": "tyr",
  "email": "tre@example.com",
  "password": "Mh&55r58r55",
  "first_name": "John",
  "last_name": "Doe",
  "mobile": "1234567890",
  "birth_date": "1990-01-01"
}
###
POST http://localhost:3000/users/signin
Content-Type: application/json

{
  "email": "tre@example.com",
  "password": "Mh&55r58r55444444"
}
###
GET  http://localhost:3000/users/signout 
Authorization:xgrrkH3vkrfklzBsJ3M3jWcwJUhrhw 
###
#INFORMATION
GET http://localhost:3000/users/53
Authorization:0LExz9in2mqO43v8eyjD
###
#UPDATE INFORMATION
PUT http://localhost:3000/users/54
Content-Type: application/json
Authorization:YrDWOklpKkaWl2OUTcH9lLTk5pacUc

{
  "first_name": "ukuukuku",
  "birth_date": "1997-01-01T00:00:00.000Z"
}
###
#DELETE USER ACCOUNT 
DELETE  http://localhost:3000/users/32
Authorization:YrDWOklpKkaWl2OUTcH9lLTk5pacUc
###
PUT  http://localhost:3000/users/change-password
Content-Type: application/json
Authorization:vaFvCDICNKX44HOAuX3YqYhVFk1fXO

{
  "currentPassword":"Mh&55r58r55",
  "newPassword":"Mh&55r58r55444444"
}

###
PUT  http://localhost:3000/users/change-username
Content-Type: application/json
Authorization:0LExz9in2mqO43v8eyjD

{
"newUsername":"kratos"
}

################################################

#REVIEWS
POST   http://localhost:3000/reviews/7
Content-Type: application/json
Authorization:0LExz9in2mqO43v8eyjD

{
  "rating":5,
  "comment":"gtgrgr"
}

###

PUT   http://localhost:3000/reviews/4
Content-Type: application/json
Authorization:0LExz9in2mqO43v8eyjD

{
  "rating":2,
  "comment":"Mh&gegegegerg"
}
###
DELETE    http://localhost:3000/reviews/7
Authorization:0LExz9in2mqO43v8eyjD

###
GET http://localhost:3000/reviews
Authorization:0LExz9in2mqO43v8eyjD
#######################################################

#WISHLIST
####
GET http://localhost:3000/wishlist
Authorization:0LExz9in2mqO43v8eyjD
###
DELETE  http://localhost:3000/wishlist
Authorization:0LExz9in2mqO43v8eyjD
###
DELETE  http://localhost:3000/wishlist/product/16
Authorization:0LExz9in2mqO43v8eyjD
###
POST   http://localhost:3000/wishlist/product
Content-Type: application/json
Authorization:0LExz9in2mqO43v8eyjD

{
  "product_id":16,
  "comment":"i like it "
}
###
POST   http://localhost:3000/wishlist/toggle
Content-Type: application/json
Authorization:Qyjk2h5rCvfpXb2eoV924vv3M0iQQ8

{
  "product_id":16
}


